package com.example.ding.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.myapplication.model.http.bean.Bean_Lei;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEAN__LEI".
*/
public class Bean_LeiDao extends AbstractDao<Bean_Lei, Long> {

    public static final String TABLENAME = "BEAN__LEI";

    /**
     * Properties of entity Bean_Lei.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Gongong = new Property(3, String.class, "gongong", false, "GONGONG");
        public final static Property Shijian = new Property(4, String.class, "shijian", false, "SHIJIAN");
    }


    public Bean_LeiDao(DaoConfig config) {
        super(config);
    }
    
    public Bean_LeiDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEAN__LEI\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"NAME\" TEXT," + // 2: name
                "\"GONGONG\" TEXT," + // 3: gongong
                "\"SHIJIAN\" TEXT);"); // 4: shijian
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEAN__LEI\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Bean_Lei entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String gongong = entity.getGongong();
        if (gongong != null) {
            stmt.bindString(4, gongong);
        }
 
        String shijian = entity.getShijian();
        if (shijian != null) {
            stmt.bindString(5, shijian);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Bean_Lei entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String gongong = entity.getGongong();
        if (gongong != null) {
            stmt.bindString(4, gongong);
        }
 
        String shijian = entity.getShijian();
        if (shijian != null) {
            stmt.bindString(5, shijian);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Bean_Lei readEntity(Cursor cursor, int offset) {
        Bean_Lei entity = new Bean_Lei( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gongong
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // shijian
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Bean_Lei entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGongong(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setShijian(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Bean_Lei entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Bean_Lei entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Bean_Lei entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
